### ISSUE TITLE
Regarding generation of FDR score pertaining to each community

### ISSUE THREAD

**Issue by NTDevika** [cdanielmachado/HiOrCo#1]
Dear  Daniel,

Now with hiorco, I could only generate list of community with different sizes.
I would like to know the possibility of printing p-value corresponding to each of  community sizes - say size of 2 to 10.
Hope I am clear.

**Comment by cdanielmachado** [comment]
For each community size, there is table (in a pandas dataframe) with intermediate results, including p-values, which is not exported, but you can easily do it with an extra line of code: `scores.to_csv(filename)`.
